version: "3.5"

services:
  jekyll-ml-text_dev:
    image: docker_jekyll-ml-text_dev
    environment:
      - JEKYLL_ENV
    ports:
      - 4000:4000
    container_name: jekyll-ml-text_default
    volumes:
      - ..:/usr/src/app
    stdin_open: true
    tty: true
    command: bundle exec jekyll serve -H 0.0.0.0 -t
